// NOTE: Due to file size constraints, this file contains detailed data for the first 5 jobs from each category.
// In production, all 33 jobs would be fully detailed here.

export interface CareerPathway {
    id: string;
    title: string;
    category: 'SDGs & ESG' | 'Future Tech' | 'In-Demand Now';
    salary: string;
    growth: string;
    icon: string;
    shortDescription: string;
    fullDescription: string;
    keySkills: string[];
    requiredCourses: string[];
    optionalCourses: string[];
    timeToMastery: string;
    careerProgression: string[];
}

export const CAREER_PATHWAYS: CareerPathway[] = [
    // SDGs & ESG CATEGORY - Sample of 10 jobs
    {
        id: 'sustainability-consultant',
        title: 'Sustainability Consultant',
        category: 'SDGs & ESG',
        salary: '$75K - $130K',
        growth: '+22%',
        icon: '🌱',
        shortDescription: 'Help organizations achieve sustainability goals and ESG compliance',
        fullDescription: 'As a Sustainability Consultant, you\'ll work with corporations, governments, and NGOs to develop and implement sustainable practices that align with the UN Sustainable Development Goals. You\'ll conduct ESG audits, create sustainability roadmaps, and measure environmental impact while ensuring regulatory compliance.',
        keySkills: ['ESG Reporting', 'Carbon Footprint Analysis', 'Stakeholder Engagement', 'Sustainability Metrics', 'Regulatory Compliance'],
        requiredCourses: ['Circular Economy Models', 'Sustainable Urban Planning', 'AI Governance'],
        optionalCourses: ['Digital Transformation', 'Data Analytics Fundamentals'],
        timeToMastery: '12-18 months',
        careerProgression: ['Junior Sustainability Analyst', 'Sustainability Consultant', 'Head of Sustainability', 'Chief Sustainability Officer']
    },
    {
        id: 'esg-data-analyst',
        title: 'ESG Data Analyst',
        category: 'SDGs & ESG',
        salary: '$70K - $120K',
        growth: '+28%',
        icon: '📊',
        shortDescription: 'Analyze and report on environmental, social, and governance metrics',
        fullDescription: 'ESG Data Analysts collect, analyze, and interpret corporate sustainability data to support investment decisions and regulatory reporting. You\'ll work with large datasets, create impactful visualizations, and provide insights that drive sustainable business practices.',
        keySkills: ['Data Analytics', 'ESG Frameworks (GRI, SASB)', 'SQL & Python', 'Data Visualization', 'Statistical Analysis'],
        requiredCourses: ['Data Analytics Fundamentals', 'AI Governance', 'Circular Economy Models'],
        optionalCourses: ['Advanced Renewable Energy Systems', 'Digital Transformation'],
        timeToMastery: '10-14 months',
        careerProgression: ['ESG Associate', 'ESG Data Analyst', 'Senior ESG Analyst', 'ESG Analytics Manager']
    },
    {
        id: 'green-tech-innovator',
        title: 'Green Tech Innovator',
        category: 'SDGs & ESG',
        salary: '$85K - $150K',
        growth: '+35%',
        icon: '💡',
        shortDescription: 'Design sustainable technology solutions for environmental challenges',
        fullDescription: 'Green Tech Innovators combine engineering, sustainability, and entrepreneurship to create breakthrough solutions for climate change, renewable energy, and resource efficiency. You\'ll prototype clean technologies, secure funding, and bring sustainable innovations to market.',
        keySkills: ['Sustainable Design', 'Renewable Energy Tech', 'Prototyping', 'Entrepreneurship', 'Clean Tech Funding'],
        requiredCourses: ['Advanced Renewable Energy Systems', 'Circular Economy Models', 'Digital Transformation'],
        optionalCourses: ['AI for Higher Education', 'Blockchain Identity Passport'],
        timeToMastery: '18-24 months',
        careerProgression: ['Junior Cleantech Engineer', 'Green Tech Developer', 'Green Tech Innovator', 'Cleantech Entrepreneur']
    },
    {
        id: 'carbon-accounting-specialist',
        title: 'Carbon Accounting Specialist',
        category: 'SDGs & ESG',
        salary: '$68K - $115K',
        growth: '+30%',
        icon: '🌍',
        shortDescription: 'Measure and manage organizational carbon footprints',
        fullDescription: 'Carbon Accounting Specialists quantify greenhouse gas emissions across value chains, develop decarbonization strategies, and help organizations achieve net-zero targets. You\'ll master carbon accounting standards, conduct lifecycle assessments, and create carbon reduction roadmaps.',
        keySkills: ['GHG Protocol', 'Lifecycle Assessment', 'Carbon Markets', 'Scope 1/2/3 Emissions', 'Sustainability Reporting'],
        requiredCourses: ['Circular Economy Models', 'Data Analytics Fundamentals', 'Sustainable Urban Planning'],
        optionalCourses: ['Advanced Renewable Energy Systems', 'AI Governance'],
        timeToMastery: '12-16 months',
        careerProgression: ['Carbon Analyst', 'Carbon Accounting Specialist', 'Carbon Manager', 'Head of Decarbonization']
    },
    {
        id: 'impact-investment-analyst',
        title: 'Impact Investment Analyst',
        category: 'SDGs & ESG',
        salary: '$80K - $140K',
        growth: '+25%',
        icon: '💰',
        shortDescription: 'Invest in companies creating measurable social and environmental impact',
        fullDescription: 'Impact Investment Analysts evaluate investments that generate positive social and environmental outcomes alongside financial returns. You\'ll assess SDG alignment, measure impact metrics, and manage portfolios focused on solving global challenges while delivering competitive returns.',
        keySkills: ['Impact Measurement', 'Financial Analysis', 'SDG Alignment', 'Due Diligence', 'Portfolio Management'],
        requiredCourses: ['AI Governance', 'Circular Economy Models', 'Data Analytics Fundamentals'],
        optionalCourses: ['Digital Transformation', 'Sustainable Urban Planning'],
        timeToMastery: '14-20 months',
        careerProgression: ['Impact Analyst', 'Impact Investment Analyst', 'Senior Impact Analyst', 'Impact Fund Manager']
    },
    {
        id: 'circular-economy-designer',
        title: 'Circular Economy Designer',
        category: 'SDGs & ESG',
        salary: '$73K - $125K',
        growth: '+27%',
        icon: '♻️',
        shortDescription: 'Design products and systems for zero-waste circularity',
        fullDescription: 'Circular Economy Designers reimagine products, packaging, and business models to eliminate waste and keep materials in continuous use. You\'ll apply design thinking, lifecycle thinking, and systems thinking to create regenerative solutions.',
        keySkills: ['Circular Design', 'Material Science', 'Lifecycle Thinking', 'Cradle-to-Cradle', 'Systems Thinking'],
        requiredCourses: ['Circular Economy Models', 'Sustainable Urban Planning', 'Digital Transformation'],
        optionalCourses: ['Advanced Renewable Energy Systems', 'AI Governance'],
        timeToMastery: '16-22 months',
        careerProgression: ['Sustainability Designer', 'Circular Economy Designer', 'Lead Circular Designer', 'Director of Circular Innovation']
    },
    {
        id: 'climate-policy-advisor',
        title: 'Climate Policy Advisor',
        category: 'SDGs & ESG',
        salary: '$75K - $135K',
        growth: '+20%',
        icon: '🏛️',
        shortDescription: 'Shape government and corporate climate policies',
        fullDescription: 'Climate Policy Advisors work at the intersection of science, economics, and governance to develop effective climate action policies. You\'ll analyze climate legislation, advise decision-makers, and design policy frameworks.',
        keySkills: ['Climate Science', 'Policy Analysis', 'Stakeholder Management', 'Advocacy', 'Regulatory Frameworks'],
        requiredCourses: ['AI Governance', 'Sustainable Urban Planning', 'Circular Economy Models'],
        optionalCourses: ['Data Analytics Fundamentals', 'Digital Transformation'],
        timeToMastery: '18-24 months',
        careerProgression: ['Policy Analyst', 'Climate Policy Advisor', 'Senior Policy Advisor', 'Chief Policy Officer']
    }, {
        id: 'biodiversity-specialist',
        title: 'Biodiversity Specialist',
        category: 'SDGs & ESG',
        salary: '$65K - $110K',
        growth: '+18%',
        icon: '🦋',
        shortDescription: 'Protect ecosystems and integrate biodiversity into business',
        fullDescription: 'Biodiversity Specialists help organizations assess and mitigate their impact on nature. You\'ll conduct biodiversity risk assessments, develop nature-positive strategies, and ensure compliance with emerging biodiversity regulations.',
        keySkills: ['Ecosystem Assessment', 'TNFD Framework', 'Conservation Biology', 'Biodiversity Metrics', 'Environmental Impact Assessment'],
        requiredCourses: ['Circular Economy Models', 'Sustainable Urban Planning', 'Data Analytics Fundamentals'],
        optionalCourses: ['AI Governance', 'Advanced Renewable Energy Systems'],
        timeToMastery: '14-18 months',
        careerProgression: ['Environmental Analyst', 'Biodiversity Specialist', 'Biodiversity Manager', 'Head of Nature Strategy']
    },
    {
        id: 'renewable-energy-project-manager',
        title: 'Renewable Energy Project Manager',
        category: 'SDGs & ESG',
        salary: '$82K - $145K',
        growth: '+32%',
        icon: '⚡',
        shortDescription: 'Lead solar, wind, and clean energy infrastructure projects',
        fullDescription: 'Renewable Energy Project Managers oversee the development, financing, and execution of clean energy projects from concept to operation. You\'ll coordinate engineers, investors, and contractors to deliver renewable installations on time and budget.',
        keySkills: ['Project Management', 'Renewable Energy Tech', 'Stakeholder Coordination', 'Risk Management', 'Energy Economics'],
        requiredCourses: ['Advanced Renewable Energy Systems', 'Digital Transformation', 'Sustainable Urban Planning'],
        optionalCourses: ['Circular Economy Models', 'AI Governance'],
        timeToMastery: '16-24 months',
        careerProgression: ['Energy Analyst', 'Project Coordinator', 'Renewable Energy PM', 'Director of Energy Projects']
    },
    {
        id: 'social-impact-strategist',
        title: 'Social Impact Strategist',
        category: 'SDGs & ESG',
        salary: '$70K - $125K',
        growth: '+24%',
        icon: '🤝',
        shortDescription: 'Design programs that create measurable social change',
        fullDescription: 'Social Impact Strategists develop and execute initiatives that address inequality, poverty, education, and health challenges. You\'ll work with corporates, foundations, and governments to design theory-of-change models and measure impact.',
        keySkills: ['Theory of Change', 'Impact Measurement', 'Program Design', 'Stakeholder Engagement', 'Social Innovation'],
        requiredCourses: ['AI Governance', 'Sustainable Urban Planning', 'Digital Transformation'],
        optionalCourses: ['Circular Economy Models', 'Data Analytics Fundamentals'],
        timeToMastery: '12-18 months',
        careerProgression: ['Program Officer', 'Social Impact Strategist', 'Head of Impact', 'Chief Impact Officer']
    },

    // FUTURE TECH CATEGORY - Sample of 12 jobs
    {
        id: 'ai-ethics-officer',
        title: 'AI Ethics Officer',
        category: 'Future Tech',
        salary: '$95K - $170K',
        growth: '+45%',
        icon: '🤖',
        shortDescription: 'Ensure responsible and ethical AI development and deployment',
        fullDescription: 'AI Ethics Officers establish frameworks and guidelines to ensure AI systems are developed and deployed responsibly. You\'ll review AI models for bias, create ethical AI policies, conduct algorithmic audits, and ensure compliance with emerging AI regulations.',
        keySkills: ['AI Governance', 'Algorithmic Fairness', 'Ethics Frameworks', 'Bias Detection', 'AI Regulation'],
        requiredCourses: ['AI Governance', 'AI for Higher Education', 'Data Analytics Fundamentals'],
        optionalCourses: ['Digital Transformation', 'Blockchain Identity Passport'],
        timeToMastery: '14-20 months',
        careerProgression: ['AI Policy Analyst', 'AI Ethics Specialist', 'AI Ethics Officer', 'Chief AI Ethics Officer']
    },
    {
        id: 'prompt-engineer',
        title: 'Prompt Engineer',
        category: 'Future Tech',
        salary: '$85K - $150K',
        growth: '+60%',
        icon: '✍️',
        shortDescription: 'Design and optimize prompts for Large Language Models',
        fullDescription: 'Prompt Engineers craft sophisticated instructions that unlock the full potential of AI language models. You\'ll develop prompt templates, optimize outputs, build AI-powered tools, and help organizations leverage LLMs for content creation, analysis, and automation.',
        keySkills: ['LLM Understanding', 'Prompt Design', 'AI Tool Development', 'Natural Language Processing', 'API Integration'],
        requiredCourses: ['AI for Higher Education', 'AI Governance', 'Digital Transformation'],
        optionalCourses: ['Data Analytics Fundamentals', 'Mastering SLM'],
        timeToMastery: '8-12 months',
        careerProgression: ['AI Content Creator', 'Prompt Engineer', 'Senior Prompt Engineer', 'AI Product Manager']
    },
    {
        id: 'quantum-computing-developer',
        title: 'Quantum Computing Developer',
        category: 'Future Tech',
        salary: '$120K - $200K',
        growth: '+55%',
        icon: '⚛️',
        shortDescription: 'Build applications leveraging quantum computing power',
        fullDescription: 'Quantum Computing Developers write algorithms and applications that harness quantum mechanics to solve problems impossible for classical computers. You\'ll work with quantum programming languages and design quantum circuits.',
        keySkills: ['Quantum Algorithms', 'Qiskit/Cirq', 'Linear Algebra', 'Quantum Circuit Design', 'Python'],
        requiredCourses: ['AI for Higher Education', 'Data Analytics Fundamentals', 'Advanced Renewable Energy Systems'],
        optionalCourses: ['AI Governance', 'Digital Transformation'],
        timeToMastery: '24-36 months',
        careerProgression: ['Quantum Research Assistant', 'Quantum Developer', 'Senior Quantum Engineer', 'Quantum Computing Architect']
    },
    {
        id: 'blockchain-architect',
        title: 'Blockchain Architect',
        category: 'Future Tech',
        salary: '$110K - $185K',
        growth: '+40%',
        icon: '🔗',
        shortDescription: 'Design decentralized systems and Web3 solutions',
        fullDescription: 'Blockchain Architects design and implement distributed ledger solutions for finance, supply chain, identity, and governance. You\'ll architect smart contracts, build decentralized applications (dApps), and ensure security.',
        keySkills: ['Smart Contracts', 'Solidity/Rust', 'Cryptography', 'DApp Development', 'Consensus Mechanisms'],
        requiredCourses: ['Blockchain Identity Passport', 'AI Governance', 'Digital Transformation'],
        optionalCourses: ['Data Analytics Fundamentals', 'AI for Higher Education'],
        timeToMastery: '18-28 months',
        careerProgression: ['Blockchain Developer', 'Blockchain Architect', 'Lead Blockchain Engineer', 'Web3 CTO']
    },
    {
        id: 'metaverse-experience-designer',
        title: 'Metaverse Experience Designer',
        category: 'Future Tech',
        salary: '$88K - $155K',
        growth: '+50%',
        icon: '🥽',
        shortDescription: 'Create immersive virtual worlds and experiences',
        fullDescription: 'Metaverse Experience Designers build engaging virtual environments for gaming, events, education, and commerce. You\'ll combine 3D design, storytelling, and user experience principles to create compelling metaverse experiences.',
        keySkills: ['3D Design (Unity/Unreal)', 'VR/AR Development', 'Spatial UX', 'Avatar Systems', 'Virtual Economy Design'],
        requiredCourses: ['Digital Transformation', 'AI for Higher Education', 'Blockchain Identity Passport'],
        optionalCourses: ['AI Governance', 'Data Analytics Fundamentals'],
        timeToMastery: '16-22 months',
        careerProgression: ['3D Artist', 'VR Developer', 'Metaverse Designer', 'Chief Metaverse Officer']
    },
    {
        id: 'ai-ml-engineer',
        title: 'AI/ML Engineer',
        category: 'Future Tech',
        salary: '$105K - $180K',
        growth: '+42%',
        icon: '🧠',
        shortDescription: 'Build and deploy machine learning models at scale',
        fullDescription: 'AI/ML Engineers develop intelligent systems that learn from data and make predictions. You\'ll train deep learning models, deploy ML pipelines, optimize algorithms, and integrate AI capabilities into products.',
        keySkills: ['Python/TensorFlow', 'Deep Learning', 'MLOps', 'Model Deployment', 'Data Engineering'],
        requiredCourses: ['AI for Higher Education', 'Data Analytics Fundamentals', 'AI Governance'],
        optionalCourses: ['Digital Transformation', 'Mastering SLM'],
        timeToMastery: '16-24 months',
        careerProgression: ['Data Scientist', 'ML Engineer', 'Senior ML Engineer', 'ML Architecture Lead']
    },
    {
        id: 'biotech-ai-specialist',
        title: 'Biotech AI Specialist',
        category: 'Future Tech',
        salary: '$100K - $175K',
        growth: '+38%',
        icon: '🧬',
        shortDescription: 'Apply AI to accelerate drug discovery and genetic research',
        fullDescription: 'Biotech AI Specialists use machine learning to analyze biological data, predict protein structures, design new molecules, and accelerate drug discovery. You\'ll bridge biology and AI to revolutionize healthcare.',
        keySkills: ['Computational Biology', 'Protein Folding AI', 'Genomics', 'Drug Discovery ML', 'Bioinformatics'],
        requiredCourses: ['AI for Higher Education', 'AI Governance', 'Data Analytics Fundamentals'],
        optionalCourses: ['Advanced Renewable Energy Systems', 'Digital Transformation'],
        timeToMastery: '20-30 months',
        careerProgression: ['Bioinformatics Analyst', 'Biotech AI Specialist', 'Computational Biology Lead', 'AI Biotech Director']
    },
    {
        id: 'edge-computing-engineer',
        title: 'Edge Computing Engineer',
        category: 'Future Tech',
        salary: '$95K - $165K',
        growth: '+35%',
        icon: '📡',
        shortDescription: 'Deploy AI and processing power at the network edge',
        fullDescription: 'Edge Computing Engineers design systems that process data near its source rather than in centralized cloud datacenters. You\'ll optimize for low latency and build distributed AI models for IoT devices.',
        keySkills: ['IoT Architecture', 'Edge AI Deployment', 'Network Optimization', 'Embedded Systems', 'Real-Time Processing'],
        requiredCourses: ['AI for Higher Education', 'Digital Transformation', 'Data Analytics Fundamentals'],
        optionalCourses: ['Advanced Renewable Energy Systems', 'AI Governance'],
        timeToMastery: '14-20 months',
        careerProgression: ['IoT Developer', 'Edge Computing Engineer', 'Senior Edge Engineer', 'Edge Architecture Director']
    },
    {
        id: 'digital-twin-specialist',
        title: 'Digital Twin Specialist',
        category: 'Future Tech',
        salary: '$92K - $160K',
        growth: '+40%',
        icon: '👥',
        shortDescription: 'Create virtual replicas of physical systems for optimization',
        fullDescription: 'Digital Twin Specialists build virtual replicas of factories, cities, products, and supply chains to simulate, predict, and optimize real-world operations. You\'ll integrate IoT data, AI models, and 3D visualization.',
        keySkills: ['IoT Integration', '3D Modeling', 'Simulation', 'Data Fusion', 'Predictive Analytics'],
        requiredCourses: ['Digital Transformation', 'AI for Higher Education', 'Data Analytics Fundamentals'],
        optionalCourses: ['Sustainable Urban Planning', 'Advanced Renewable Energy Systems'],
        timeToMastery: '16-22 months',
        careerProgression: ['Simulation Engineer', 'Digital Twin Developer', 'Digital Twin Specialist', 'Digital Twin Architect']
    },
    {
        id: 'neuromorphic-computing-engineer',
        title: 'Neuromorphic Computing Engineer',
        category: 'Future Tech',
        salary: '$115K - $190K',
        growth: '+33%',
        icon: '🧪',
        shortDescription: 'Design brain-inspired computing systems',
        fullDescription: 'Neuromorphic Computing Engineers develop hardware and software that mimic the human brain\'s neural architecture. You\'ll design energy-efficient chips and create spiking neural networks.',
        keySkills: ['Neuromorphic Hardware', 'Spiking Neural Networks', 'Brain-Inspired Computing', 'Low-Power AI', 'Neuroscience Basics'],
        requiredCourses: ['AI for Higher Education', 'Advanced Renewable Energy Systems', 'Digital Transformation'],
        optionalCourses: ['AI Governance', 'Data Analytics Fundamentals'],
        timeToMastery: '24-32 months',
        careerProgression: ['Neural Computing Researcher', 'Neuromorphic Engineer', 'Senior Neuromorphic Engineer', 'Neuromorphic Architecture Lead']
    },
    {
        id: 'autonomous-systems-engineer',
        title: 'Autonomous Systems Engineer',
        category: 'Future Tech',
        salary: '$108K - $185K',
        growth: '+38%',
        icon: '🚗',
        shortDescription: 'Build self-driving vehicles, drones, and robots',
        fullDescription: 'Autonomous Systems Engineers develop the perception, planning, and control systems that enable vehicles and robots to operate without human intervention. You\'ll work with sensor fusion, computer vision, and path planning.',
        keySkills: ['Computer Vision', 'Sensor Fusion', 'Path Planning', 'ROS (Robot Operating System)', 'Reinforcement Learning'],
        requiredCourses: ['AI for Higher Education', 'Digital Transformation', 'Data Analytics Fundamentals'],
        optionalCourses: ['AI Governance', 'Advanced Renewable Energy Systems'],
        timeToMastery: '18-26 months',
        careerProgression: ['Robotics Engineer', 'Autonomous Systems Engineer', 'Senior Autonomy Engineer', 'Autonomous Systems Architect']
    },
    {
        id: 'synthetic-data-engineer',
        title: 'Synthetic Data Engineer',
        category: 'Future Tech',
        salary: '$90K - $155K',
        growth: '+48%',
        icon: '🎲',
        shortDescription: 'Generate realistic artificial data for AI training',
        fullDescription: 'Synthetic Data Engineers create artificial datasets that preserve statistical properties of real data while protecting privacy. You\'ll use GANs, simulation, and advanced techniques to generate training data for AI models.',
        keySkills: ['Generative AI (GANs)', 'Data Privacy', 'Simulation', 'Statistical Modeling', 'Data Augmentation'],
        requiredCourses: ['AI for Higher Education', 'AI Governance', 'Data Analytics Fundamentals'],
        optionalCourses: ['Digital Transformation', 'Blockchain Identity Passport'],
        timeToMastery: '12-18 months',
        careerProgression: ['Data Engineer', 'Synthetic Data Engineer', 'Senior Synthetic Data Engineer', 'Data Generation Architect']
    },

    // IN-DEMAND NOW CATEGORY - Sample of 11 jobs
    {
        id: 'cloud-architect',
        title: 'Cloud Solutions Architect',
        category: 'In-Demand Now',
        salary: '$110K - $180K',
        growth: '+25%',
        icon: '☁️',
        shortDescription: 'Design and manage scalable cloud infrastructure',
        fullDescription: 'Cloud Solutions Architects design, implement, and manage cloud infrastructure across AWS, Azure, and GCP. You\'ll architect multi-cloud solutions, optimize costs, ensure security and compliance.',
        keySkills: ['AWS/Azure/GCP', 'Cloud Architecture', 'DevOps', 'Kubernetes', 'Infrastructure as Code'],
        requiredCourses: ['Digital Transformation', 'Data Analytics Fundamentals', 'AI Governance'],
        optionalCourses: ['AI for Higher Education', 'Blockchain Identity Passport'],
        timeToMastery: '12-18 months',
        careerProgression: ['Cloud Engineer', 'Cloud Architect', 'Principal Cloud Architect', 'VP of Cloud Infrastructure']
    },
    {
        id: 'cybersecurity-analyst',
        title: 'Cybersecurity Analyst',
        category: 'In-Demand Now',
        salary: '$80K - $140K',
        growth: '+35%',
        icon: '🔒',
        shortDescription: 'Protect organizations from cyber threats and breaches',
        fullDescription: 'Cybersecurity Analysts defend networks, systems, and data from cyber attacks. You\'ll monitor for threats, conduct vulnerability assessments, respond to incidents, and implement security controls.',
        keySkills: ['Threat Detection', 'Penetration Testing', 'SIEM Tools', 'Incident Response', 'Security Frameworks'],
        requiredCourses: ['DigitalTransformation', 'AI Governance', 'Blockchain Identity Passport'],
        optionalCourses: ['Data Analytics Fundamentals', 'AI for Higher Education'],
        timeToMastery: '10-16 months',
        careerProgression: ['Security Analyst', 'Cybersecurity Analyst', 'Security Engineer', 'Chief Information Security Officer']
    },
    {
        id: 'data-scientist',
        title: 'Data Scientist',
        category: 'In-Demand Now',
        salary: '$95K - $165K',
        growth: '+36%',
        icon: '📈',
        shortDescription: 'Extract insights from data to drive business decisions',
        fullDescription: 'Data Scientists analyze complex datasets to uncover patterns, build predictive models, and generate actionable insights. You\'ll use statistics, machine learning, and data visualization to solve business problems.',
        keySkills: ['Python/R', 'Machine Learning', 'Statistical Analysis', 'Data Visualization', 'SQL'],
        requiredCourses: ['Data Analytics Fundamentals', 'AI for Higher Education', 'Digital Transformation'],
        optionalCourses: ['AI Governance', 'Mastering SLM'],
        timeToMastery: '12-18 months',
        careerProgression: ['Data Analyst', 'Data Scientist', 'Senior Data Scientist', 'Chief Data Officer']
    },
    {
        id: 'devops-engineer',
        title: 'DevOps Engineer',
        category: 'In-Demand Now',
        salary: '$95K - $160K',
        growth: '+30%',
        icon: '⚙️',
        shortDescription: 'Automate and streamline software development and deployment',
        fullDescription: 'DevOps Engineers bridge the gap between development and operations, creating CI/CD pipelines, automating infrastructure, and enabling rapid, reliable software releases.',
        keySkills: ['CI/CD Pipelines', 'Docker/Kubernetes', 'Terraform', 'Git', 'Monitoring (Prometheus/Grafana)'],
        requiredCourses: ['Digital Transformation', 'Data Analytics Fundamentals', 'AI for Higher Education'],
        optionalCourses: ['AI Governance', 'Blockchain Identity Passport'],
        timeToMastery: '10-14 months',
        careerProgression: ['Systems Administrator', 'DevOps Engineer', 'Senior DevOps Engineer', 'Principal DevOps Architect']
    },
    {
        id: 'full-stack-developer',
        title: 'Full Stack Developer',
        category: 'In-Demand Now',
        salary: '$85K - $145K',
        growth: '+22%',
        icon: '💻',
        shortDescription: 'Build complete web applications from frontend to backend',
        fullDescription: 'Full Stack Developers create end-to-end web applications, working across frontend, backend, and databases. You\'ll master modern frameworks, RESTful APIs, databases, and cloud deployment.',
        keySkills: ['React/Next.js', 'Node.js/Python', 'SQL/NoSQL', 'REST APIs', 'Cloud Deployment'],
        requiredCourses: ['Digital Transformation', 'Data Analytics Fundamentals', 'AI for Higher Education'],
        optionalCourses: ['Blockchain Identity Passport', 'AI Governance'],
        timeToMastery: '10-16 months',
        careerProgression: ['Junior Developer', 'Full Stack Developer', 'Senior Full Stack', 'Engineering Manager']
    },
    {
        id: 'product-manager',
        title: 'Technical Product Manager',
        category: 'In-Demand Now',
        salary: '$100K - $175K',
        growth: '+20%',
        icon: '🎯',
        shortDescription: 'Define and deliver technology products users love',
        fullDescription: 'Technical Product Managers bridge business, engineering, and design to create successful products. You\'ll define product vision, prioritize features, analyze user data, and work cross-functionally.',
        keySkills: ['Product Strategy', 'User Research', 'Agile/Scrum', 'Data Analysis', 'Technical Understanding'],
        requiredCourses: ['Digital Transformation', 'AI Governance', 'Data Analytics Fundamentals'],
        optionalCourses: ['AI for Higher Education', 'Sustainable Urban Planning'],
        timeToMastery: '14-20 months',
        careerProgression: ['Associate PM', 'Product Manager', 'Senior PM', 'VP of Product']
    },
    {
        id: 'ux-designer',
        title: 'UX/UI Designer',
        category: 'In-Demand Now',
        salary: '$75K - $130K',
        growth: '+16%',
        icon: '🎨',
        shortDescription: 'Create intuitive, delightful user experiences',
        fullDescription: 'UX/UI Designers research user needs, design interfaces, and create seamless digital experiences. You\'ll conduct user research, create wireframes and prototypes, and design beautiful interfaces.',
        keySkills: ['Figma/Adobe XD', 'User Research', 'Prototyping', 'Interaction Design', 'Design Systems'],
        requiredCourses: ['Digital Transformation', 'AI for Higher Education', 'Data Analytics Fundamentals'],
        optionalCourses: ['AI Governance', 'Sustainable Urban Planning'],
        timeToMastery: '8-14 months',
        careerProgression: ['Junior Designer', 'UX/UI Designer', 'Senior Designer', 'Head of Design']
    },
    {
        id: 'digital-marketer',
        title: 'Digital Marketing Specialist',
        category: 'In-Demand Now',
        salary: '$60K - $110K',
        growth: '+10%',
        icon: '📱',
        shortDescription: 'Drive growth through data-driven digital marketing',
        fullDescription: 'Digital Marketing Specialists leverage SEO, content, paid ads, and analytics to acquire and engage customers online. You\'ll create campaigns, analyze performance data, and optimize conversion funnels.',
        keySkills: ['SEO/SEM', 'Content Marketing', 'Google Analytics', 'Social Media', 'Marketing Automation'],
        requiredCourses: ['Digital Transformation', 'Data Analytics Fundamentals', 'AI for Higher Education'],
        optionalCourses: ['AI Governance', 'Mastering SLM'],
        timeToMastery: '6-10 months',
        careerProgression: ['Marketing Coordinator', 'Digital Marketing Specialist', 'Marketing Manager', 'CMO']
    },
    {
        id: 'business-intelligence-analyst',
        title: 'Business Intelligence Analyst',
        category: 'In-Demand Now',
        salary: '$70K - $120K',
        growth: '+14%',
        icon: '📊',
        shortDescription: 'Turn business data into strategic insights',
        fullDescription: 'Business Intelligence Analysts transform raw data into dashboards, reports, and insights that guide strategic decisions. You\'ll work with BI tools like Tableau and Power BI.',
        keySkills: ['Tableau/Power BI', 'SQL', 'Data Warehousing', 'Data Modeling', 'Business Analysis'],
        requiredCourses: ['Data Analytics Fundamentals', 'Digital Transformation', 'AI Governance'],
        optionalCourses: ['AI for Higher Education', 'Sustainable Urban Planning'],
        timeToMastery: '8-12 months',
        careerProgression: ['Data Analyst', 'BI Analyst', 'Senior BI Analyst', 'BI Manager']
    },
    {
        id: 'salesforce-developer',
        title: 'Salesforce Developer',
        category: 'In-Demand Now',
        salary: '$85K - $145K',
        growth: '+18%',
        icon: '⚡',
        shortDescription: 'Customize and extend Salesforce CRM platform',
        fullDescription: 'Salesforce Developers build custom applications, automations, and integrations on the Salesforce platform. You\'ll master Apex, Lightning Web Components, and Salesforce architecture.',
        keySkills: ['Apex', 'Lightning Web Components', 'Salesforce Architecture', 'SOQL', 'Integration'],
        requiredCourses: ['Digital Transformation', 'Data Analytics Fundamentals', 'AI for Higher Education'],
        optionalCourses: ['AI Governance', 'Blockchain Identity Passport'],
        timeToMastery: '10-14 months',
        careerProgression: ['Salesforce Admin', 'Salesforce Developer', 'Technical Architect', 'Salesforce CTO']
    },
    {
        id: 'change-management-consultant',
        title: 'Digital Transformation Consultant',
        category: 'In-Demand Now',
        salary: '$90K - $155K',
        growth: '+15%',
        icon: '🔄',
        shortDescription: 'Guide organizations through technology-driven change',
        fullDescription: 'Digital Transformation Consultants help organizations modernize processes, adopt new technologies, and evolve culture. You\'ll assess current state, design transformation roadmaps, and manage stakeholder buy-in.',
        keySkills: ['Change Management', 'Digital Strategy', 'Process Optimization', 'Stakeholder Management', 'Agile Transformation'],
        requiredCourses: ['Digital Transformation', 'AI Governance', 'Sustainable Urban Planning'],
        optionalCourses: ['AI for Higher Education', 'Data Analytics Fundamentals'],
        timeToMastery: '12-18 months',
        careerProgression: ['Business Analyst', 'Transformation Consultant', 'Senior Consultant', 'Partner']
    },
];

export const CAREER_CATEGORIES = [
    {
        id: 'sdg-esg',
        name: 'SDGs & ESG',
        description: 'Shape a sustainable future',
        color: 'from-green-500 to-emerald-600',
        icon: '🌍'
    },
    {
        id: 'future-tech',
        name: 'Future Tech',
        description: 'Build tomorrow\'s technology',
        color: 'from-purple-500 to-indigo-600',
        icon: '🚀'
    },
    {
        id: 'in-demand',
        name: 'In-Demand Now',
        description: 'Start earning immediately',
        color: 'from-blue-500 to-cyan-600',
        icon: '⚡'
    }
];
